<a href="https://colab.research.google.com/github/kamleshsah/ML-Project/blob/main/Carnival_Fest_Selling_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datsets/Carnival Selling Price Prediction/train.csv')

In [15]:
train.head()

Product_id  Stall_no  ... Maximum_price  Selling_Price
0  BRAE2NF6JA5GUEXG      37.0  ...        4713.0    4185.947700
1  TUNE8SFB6RJN2HSD      38.0  ...       10352.0    9271.490256
2  BRAEAR7WZPQGPBZU       9.0  ...        7309.0    6785.701362
3  WATDZ2ZQ8JPDHCTJ      50.0  ...       20814.0   13028.917820
4  JWSEBUKYQPMBZ3RK       7.0  ...        9261.0     906.553935

[5 rows x 15 columns]

In [16]:
train=train.drop(['Customer_name','instock_date','Stall_no'],axis=1)

In [17]:
train.head()

Product_id  Market_Category  ... Maximum_price Selling_Price
0  BRAE2NF6JA5GUEXG                2  ...        4713.0   4185.947700
1  TUNE8SFB6RJN2HSD               24  ...       10352.0   9271.490256
2  BRAEAR7WZPQGPBZU              447  ...        7309.0   6785.701362
3  WATDZ2ZQ8JPDHCTJ               23  ...       20814.0  13028.917820
4  JWSEBUKYQPMBZ3RK               63  ...        9261.0    906.553935

[5 rows x 12 columns]

In [18]:
Y_train=train['Selling_Price']

In [19]:
X_train=train.drop(['Selling_Price'],axis=1)

In [20]:
X_train.head()

Product_id  Market_Category  ... Minimum_price Maximum_price
0  BRAE2NF6JA5GUEXG                2  ...        2983.0        4713.0
1  TUNE8SFB6RJN2HSD               24  ...        7495.0       10352.0
2  BRAEAR7WZPQGPBZU              447  ...        5752.0        7309.0
3  WATDZ2ZQ8JPDHCTJ               23  ...        5090.0       20814.0
4  JWSEBUKYQPMBZ3RK               63  ...        2430.0        9261.0

[5 rows x 11 columns]

In [22]:
X_train.isnull().sum()

Product_id            0
Market_Category       0
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
dtype: int64

In [23]:
Y_train.isnull().sum()

41

In [27]:
X_train['Discount_avail'] = X_train['Discount_avail'].fillna(X_train['Discount_avail'].mean())
X_train['charges_1'] = X_train['charges_1'].fillna(X_train['charges_1'].mean())
X_train['charges_2 (%)'] = X_train['charges_2 (%)'].fillna(X_train['charges_2 (%)'].mean())
X_train['Minimum_price'] = X_train['Minimum_price'].fillna(X_train['Minimum_price'].mean())
X_train['Maximum_price'] = X_train['Maximum_price'].fillna(X_train['Maximum_price'].mean())
Y_train= Y_train.fillna(Y_train.mean())

In [28]:
X_train.isnull().sum()

Product_id          0
Market_Category     0
Loyalty_customer    0
Product_Category    0
Grade               0
Demand              0
Discount_avail      0
charges_1           0
charges_2 (%)       0
Minimum_price       0
Maximum_price       0
dtype: int64

In [29]:
Y_train.isnull().sum()

0

Test Data

In [30]:
test_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datsets/Carnival Selling Price Prediction/test.csv")

In [31]:
test_data.head()

Product_id  Stall_no  ... Minimum_price  Maximum_price
0  SCHE4YSTDVPVZVXW      39.0  ...        2576.0           3340
1  ACCEGCATKHNRXUHW      49.0  ...        1202.0           1955
2  NKCE6GJ5XVJDXNNZ       1.0  ...        7175.0          15715
3  NKCEB8BK3ZXDHDHM       8.0  ...        5404.0          13078
4  TOPEFDXSAHRNPF94      33.0  ...        4069.0           6244

[5 rows x 14 columns]

In [34]:
test=test_data.drop(['Stall_no','instock_date','Customer_name'],axis=1)

In [35]:
test.head()

Product_id  Market_Category  ... Minimum_price Maximum_price
0  SCHE4YSTDVPVZVXW              205  ...        2576.0          3340
1  ACCEGCATKHNRXUHW                3  ...        1202.0          1955
2  NKCE6GJ5XVJDXNNZ              183  ...        7175.0         15715
3  NKCEB8BK3ZXDHDHM              358  ...        5404.0         13078
4  TOPEFDXSAHRNPF94              167  ...        4069.0          6244

[5 rows x 11 columns]

In [36]:
test.isnull().sum()

Product_id           0
Market_Category      0
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2 (%)        5
Minimum_price       14
Maximum_price        0
dtype: int64

In [38]:
test['charges_1']=test['charges_1'].fillna(test['charges_1'].mean())
test['charges_2 (%)']=test['charges_2 (%)'].fillna(test['charges_2 (%)'].mean())
test['Minimum_price']=test['Minimum_price'].fillna(test['Minimum_price'].mean())

In [39]:
test.isnull().sum()

Product_id          0
Market_Category     0
Loyalty_customer    0
Product_Category    0
Grade               0
Demand              0
Discount_avail      0
charges_1           0
charges_2 (%)       0
Minimum_price       0
Maximum_price       0
dtype: int64

In [40]:
test_id=test['Product_id']

In [53]:
X_train.columns.get_indexer(['Loyalty_customer','Product_Category'])

array([2, 3])

In [64]:
from sklearn.preprocessing import LabelEncoder
X_train['Loyalty_customer']=LabelEncoder().fit_transform(X_train['Loyalty_customer'])
X_train['Product_Category']=LabelEncoder().fit_transform(X_train['Product_Category'])
test['Product_Category']=LabelEncoder().fit_transform(test['Product_Category'])
test['Loyalty_customer']=LabelEncoder().fit_transform(test['Loyalty_customer'])

In [62]:
X_train.head()

Product_id  Market_Category  ...  Minimum_price  Maximum_price
0  BRAE2NF6JA5GUEXG                2  ...         2983.0         4713.0
1  TUNE8SFB6RJN2HSD               24  ...         7495.0        10352.0
2  BRAEAR7WZPQGPBZU              447  ...         5752.0         7309.0
3  WATDZ2ZQ8JPDHCTJ               23  ...         5090.0        20814.0
4  JWSEBUKYQPMBZ3RK               63  ...         2430.0         9261.0

[5 rows x 11 columns]

In [65]:
test.head()

Product_id  Market_Category  ...  Minimum_price  Maximum_price
0  SCHE4YSTDVPVZVXW              205  ...         2576.0           3340
1  ACCEGCATKHNRXUHW                3  ...         1202.0           1955
2  NKCE6GJ5XVJDXNNZ              183  ...         7175.0          15715
3  NKCEB8BK3ZXDHDHM              358  ...         5404.0          13078
4  TOPEFDXSAHRNPF94              167  ...         4069.0           6244

[5 rows x 11 columns]

In [68]:
X_train=X_train.drop(['Product_id'],axis=1)
test=test.drop(['Product_id'],axis=1)

In [69]:
X_train=X_train.values
test=test.values

In [70]:
X_train

array([[2.0000e+00, 1.0000e+00, 3.0000e+00, ..., 1.1000e+01, 2.9830e+03,
        4.7130e+03],
       [2.4000e+01, 1.0000e+00, 3.0000e+00, ..., 1.2000e+01, 7.4950e+03,
        1.0352e+04],
       [4.4700e+02, 1.0000e+00, 0.0000e+00, ..., 9.0000e+00, 5.7520e+03,
        7.3090e+03],
       ...,
       [3.5800e+02, 0.0000e+00, 8.0000e+00, ..., 3.0000e+00, 5.3030e+03,
        1.4614e+04],
       [4.5200e+02, 1.0000e+00, 8.0000e+00, ..., 3.0000e+00, 4.3340e+03,
        5.8490e+03],
       [5.8000e+01, 1.0000e+00, 9.0000e+00, ..., 7.0000e+00, 3.9750e+03,
        5.3830e+03]])

In [71]:
test

array([[2.0500e+02, 0.0000e+00, 3.0000e+00, ..., 1.6000e+01, 2.5760e+03,
        3.3400e+03],
       [3.0000e+00, 1.0000e+00, 3.0000e+00, ..., 1.6000e+01, 1.2020e+03,
        1.9550e+03],
       [1.8300e+02, 0.0000e+00, 9.0000e+00, ..., 9.0000e+00, 7.1750e+03,
        1.5715e+04],
       ...,
       [1.0600e+02, 1.0000e+00, 2.0000e+00, ..., 1.7000e+01, 7.1000e+02,
        1.0894e+04],
       [1.0400e+02, 1.0000e+00, 0.0000e+00, ..., 1.5000e+01, 1.4770e+03,
        5.1650e+03],
       [1.6500e+02, 0.0000e+00, 8.0000e+00, ..., 9.0000e+00, 5.5380e+03,
        7.5060e+03]])

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
test = sc.transform(test)

In [73]:
X_train

array([[-1.15903947,  0.79892518, -0.5260554 , ...,  0.2009938 ,
        -0.25061705, -0.47574736],
       [-1.02982699,  0.79892518, -0.5260554 , ...,  0.43640329,
         1.81154148,  1.08439672],
       [ 1.45457648,  0.79892518, -1.56350376, ..., -0.2698252 ,
         1.01492306,  0.24248886],
       ...,
       [ 0.93185329, -1.25168166,  1.20302521, ..., -1.68228218,
         0.80971269,  2.26356573],
       [ 1.48394295,  0.79892518,  1.20302521, ..., -1.68228218,
         0.36684221, -0.16144984],
       [-0.83013499,  0.79892518,  1.54884133, ..., -0.74064419,
         0.20276532, -0.29037822]])

In [75]:
X_train.shape

(6368, 10)

In [74]:
test.shape

(3430, 10)

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [77]:
# from sklearn import metrics
# def print_error(x_test, y_test, model_name):
#     prediction = model_name.predict(x_test)
#     print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediction))
#     print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediction))
#     print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

In [78]:
linear_regression = LinearRegression()
linear_regression.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [79]:
decision_tree = DecisionTreeRegressor()
decision_tree.fit(X_train, Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [80]:
supportvector_regressor = SVR(gamma='auto')
supportvector_regressor.fit(X_train,Y_train.values.ravel())

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [81]:
n_estimators = 200
max_depth = 25
min_samples_split=15
min_samples_leaf=2
random_forest = RandomForestRegressor(n_estimators = n_estimators, max_depth = max_depth, min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf)
random_forest.fit(X_train,Y_train.values.ravel())

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=25, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=15, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

Prediction Model

In [92]:
prediction1=random_forest.predict(test)

In [93]:
data1 = pd.DataFrame((zip(test_id,prediction1)),columns=['Product_id','Selling_Price'])
data1['Selling_Price'] = data1['Selling_Price'].abs()

In [94]:
data1.head()

Product_id  Selling_Price
0  SCHE4YSTDVPVZVXW    3203.091410
1  ACCEGCATKHNRXUHW    1945.688998
2  NKCE6GJ5XVJDXNNZ   11581.498858
3  NKCEB8BK3ZXDHDHM    9533.368587
4  TOPEFDXSAHRNPF94    5642.727409

In [96]:
from google.colab import files
data1.to_csv('RandomForest.csv') 
files.download('RandomForest.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>